apiVersion: v1
kind: Secret
metadata:
  name: airport-secrets
  namespace: airport
type: Opaque
stringData:
  ORACLE_PASSWORD: AirportPass123
  DB_PASSWORD: AirportPass123
  JWT_SECRET: change-this-secret-to-a-long-random-production-value
  ADMIN_PASSWORD: Admin12345!
  RESEND_API_KEY: replace-with-resend-api-key
  MAIL_FROM: Airport Platform <tickets@kyrosoftgs.com>
  GRAFANA_ADMIN_PASSWORD: admin123
