CREATE SEQUENCE SEQ_USERS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_AIRPORTS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_AIRPLANES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_FLIGHTS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SEATS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RESERVATIONS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PAYMENTS START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE APP_USERS (
    ID NUMBER(19) PRIMARY KEY,
    FULL_NAME VARCHAR2(140) NOT NULL,
    EMAIL VARCHAR2(180) NOT NULL,
    PASSWORD_HASH VARCHAR2(120) NOT NULL,
    ROLE VARCHAR2(20) NOT NULL,
    PHONE VARCHAR2(40),
    DOCUMENT_NUMBER VARCHAR2(60),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_USERS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_USERS_ROLE CHECK (ROLE IN ('ADMIN','CLIENT'))
);

CREATE TABLE AIRPORTS (
    ID NUMBER(19) PRIMARY KEY,
    NAME VARCHAR2(160) NOT NULL,
    CITY VARCHAR2(100) NOT NULL,
    COUNTRY VARCHAR2(100) NOT NULL,
    IATA_CODE VARCHAR2(3) NOT NULL,
    CONSTRAINT UK_AIRPORT_IATA UNIQUE (IATA_CODE)
);

CREATE TABLE AIRPLANES (
    ID NUMBER(19) PRIMARY KEY,
    MODEL VARCHAR2(120) NOT NULL,
    CAPACITY NUMBER(6) NOT NULL,
    AIRLINE VARCHAR2(120) NOT NULL,
    CONSTRAINT CK_AIRPLANE_CAPACITY CHECK (CAPACITY > 0)
);

CREATE TABLE FLIGHTS (
    ID NUMBER(19) PRIMARY KEY,
    FLIGHT_NUMBER VARCHAR2(20) NOT NULL,
    ORIGIN_ID NUMBER(19) NOT NULL,
    DESTINATION_ID NUMBER(19) NOT NULL,
    AIRPLANE_ID NUMBER(19) NOT NULL,
    DEPARTURE_TIME TIMESTAMP NOT NULL,
    ARRIVAL_TIME TIMESTAMP NOT NULL,
    PRICE NUMBER(12,2) NOT NULL,
    AVAILABLE_SEATS NUMBER(6) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    CONSTRAINT UK_FLIGHT_NUMBER UNIQUE (FLIGHT_NUMBER),
    CONSTRAINT FK_FLIGHT_ORIGIN FOREIGN KEY (ORIGIN_ID) REFERENCES AIRPORTS(ID),
    CONSTRAINT FK_FLIGHT_DESTINATION FOREIGN KEY (DESTINATION_ID) REFERENCES AIRPORTS(ID),
    CONSTRAINT FK_FLIGHT_AIRPLANE FOREIGN KEY (AIRPLANE_ID) REFERENCES AIRPLANES(ID),
    CONSTRAINT CK_FLIGHT_STATUS CHECK (STATUS IN ('SCHEDULED','BOARDING','DEPARTED','LANDED','CANCELLED')),
    CONSTRAINT CK_FLIGHT_PRICE CHECK (PRICE > 0),
    CONSTRAINT CK_FLIGHT_ROUTE CHECK (ORIGIN_ID <> DESTINATION_ID),
    CONSTRAINT CK_FLIGHT_DATES CHECK (ARRIVAL_TIME > DEPARTURE_TIME)
);

CREATE TABLE SEATS (
    ID NUMBER(19) PRIMARY KEY,
    FLIGHT_ID NUMBER(19) NOT NULL,
    SEAT_NUMBER VARCHAR2(8) NOT NULL,
    AVAILABLE NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_SEAT_FLIGHT FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHTS(ID) ON DELETE CASCADE,
    CONSTRAINT UK_SEAT_FLIGHT_NUMBER UNIQUE (FLIGHT_ID, SEAT_NUMBER),
    CONSTRAINT CK_SEAT_AVAILABLE CHECK (AVAILABLE IN (0,1))
);

CREATE TABLE RESERVATIONS (
    ID NUMBER(19) PRIMARY KEY,
    CODE VARCHAR2(16) NOT NULL,
    USER_ID NUMBER(19) NOT NULL,
    FLIGHT_ID NUMBER(19) NOT NULL,
    SEAT_ID NUMBER(19) NOT NULL,
    STATUS VARCHAR2(24) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_RESERVATION_CODE UNIQUE (CODE),
    CONSTRAINT UK_RESERVATION_SEAT UNIQUE (SEAT_ID),
    CONSTRAINT FK_RESERVATION_USER FOREIGN KEY (USER_ID) REFERENCES APP_USERS(ID),
    CONSTRAINT FK_RESERVATION_FLIGHT FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHTS(ID),
    CONSTRAINT FK_RESERVATION_SEAT FOREIGN KEY (SEAT_ID) REFERENCES SEATS(ID),
    CONSTRAINT CK_RESERVATION_STATUS CHECK (STATUS IN ('PENDING_PAYMENT','CONFIRMED','REJECTED','CANCELLED'))
);

CREATE TABLE PAYMENTS (
    ID NUMBER(19) PRIMARY KEY,
    RESERVATION_ID NUMBER(19) NOT NULL,
    AMOUNT NUMBER(12,2) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    CARD_LAST4 VARCHAR2(4) NOT NULL,
    AUTHORIZATION_CODE VARCHAR2(40) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_PAYMENT_RESERVATION UNIQUE (RESERVATION_ID),
    CONSTRAINT FK_PAYMENT_RESERVATION FOREIGN KEY (RESERVATION_ID) REFERENCES RESERVATIONS(ID),
    CONSTRAINT CK_PAYMENT_STATUS CHECK (STATUS IN ('APPROVED','REJECTED'))
);

CREATE INDEX IX_USERS_EMAIL ON APP_USERS(EMAIL);
CREATE INDEX IX_FLIGHT_ROUTE_DATE ON FLIGHTS(ORIGIN_ID, DESTINATION_ID, DEPARTURE_TIME);
CREATE INDEX IX_RESERVATION_USER ON RESERVATIONS(USER_ID, CREATED_AT);
