INSERT INTO APP_USERS (ID, FULL_NAME, EMAIL, PASSWORD_HASH, ROLE, PHONE, DOCUMENT_NUMBER)
VALUES (SEQ_USERS.NEXTVAL, 'Administrador Airport', 'admin@airport.local', '$2a$12$9gYkiwE4C9Bj7pHhs3ffWuqBVlrK1fW0vRxDj6lIbPqEGtIS1NwUO', 'ADMIN', '+50200000000', 'ADMIN-001');

INSERT INTO AIRPORTS (ID, NAME, CITY, COUNTRY, IATA_CODE) VALUES (SEQ_AIRPORTS.NEXTVAL, 'La Aurora International Airport', 'Guatemala City', 'Guatemala', 'GUA');
INSERT INTO AIRPORTS (ID, NAME, CITY, COUNTRY, IATA_CODE) VALUES (SEQ_AIRPORTS.NEXTVAL, 'El Salvador International Airport', 'San Salvador', 'El Salvador', 'SAL');
INSERT INTO AIRPORTS (ID, NAME, CITY, COUNTRY, IATA_CODE) VALUES (SEQ_AIRPORTS.NEXTVAL, 'Miami International Airport', 'Miami', 'United States', 'MIA');

INSERT INTO AIRPLANES (ID, MODEL, CAPACITY, AIRLINE) VALUES (SEQ_AIRPLANES.NEXTVAL, 'Airbus A320neo', 36, 'Aurora Air');
INSERT INTO AIRPLANES (ID, MODEL, CAPACITY, AIRLINE) VALUES (SEQ_AIRPLANES.NEXTVAL, 'Boeing 737 MAX 8', 42, 'Pacific Wings');

INSERT INTO FLIGHTS (ID, FLIGHT_NUMBER, ORIGIN_ID, DESTINATION_ID, AIRPLANE_ID, DEPARTURE_TIME, ARRIVAL_TIME, PRICE, AVAILABLE_SEATS, STATUS)
VALUES (SEQ_FLIGHTS.NEXTVAL, 'AU101', 1, 3, 1, SYSTIMESTAMP + INTERVAL '2' DAY, SYSTIMESTAMP + INTERVAL '2' DAY + INTERVAL '3' HOUR, 219.99, 36, 'SCHEDULED');

INSERT INTO FLIGHTS (ID, FLIGHT_NUMBER, ORIGIN_ID, DESTINATION_ID, AIRPLANE_ID, DEPARTURE_TIME, ARRIVAL_TIME, PRICE, AVAILABLE_SEATS, STATUS)
VALUES (SEQ_FLIGHTS.NEXTVAL, 'PW220', 3, 2, 2, SYSTIMESTAMP + INTERVAL '3' DAY, SYSTIMESTAMP + INTERVAL '3' DAY + INTERVAL '2' HOUR, 184.50, 42, 'SCHEDULED');

DECLARE
    v_flight_id NUMBER;
    v_capacity NUMBER;
    v_letters VARCHAR2(6) := 'ABCDEF';
BEGIN
    FOR f IN (SELECT ID, AVAILABLE_SEATS FROM FLIGHTS) LOOP
        v_flight_id := f.ID;
        v_capacity := f.AVAILABLE_SEATS;
        FOR i IN 0 .. v_capacity - 1 LOOP
            INSERT INTO SEATS (ID, FLIGHT_ID, SEAT_NUMBER, AVAILABLE)
            VALUES (SEQ_SEATS.NEXTVAL, v_flight_id, TO_CHAR(TRUNC(i / 6) + 1) || SUBSTR(v_letters, MOD(i, 6) + 1, 1), 1);
        END LOOP;
    END LOOP;
END;
/
